### ISSUE TITLE
`encodeType` of typed data does not encode preset types correctly

### ISSUE THREAD

**Issue by DelevoXDG** [starknet-io/starknet.js#1002]
**Describe the bug**
`encodeType` of type data does not encode preset types correctly. 

You can verify this from the SNIP:
- [X is an u256](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md#when-x-is-a-nft-id)
- [X is a TokenAmount](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md#when-x-is-a-token-amount)
- [X is a Nft ID](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md#when-x-is-a-nft-id)

Where for every preset type, it says:
> It will be encoded as the following object.

And per the [X is an object](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md#when-x-is-an-object), every object should encoded as follows:
> `escape(name) || "(" || escape(param1_name) || ":" || escape(param1_type) || "," || ... || escape(paramN_name) || ":"|| escape(paramN_type) || ")"`
> If the object references other objects/enum which can also reference other objects/enums, the set of referenced objects/enums is collected, sorted by name, and appended to the encoding.

The spec also refers to [this repo](https://github.com/argentlabs/starknet-off-chain-signature) for examples, where preset type `u256` is [included along with its properties](https://github.com/argentlabs/starknet-off-chain-signature/blob/19ad573c0def1dc2f0a08d3d63fabdbccab1d6f6/src/struct_with_u256.cairo#L12).

**To Reproduce**
Run this test:
https://github.com/starknet-io/starknet.js/blob/fdcc7fbf5957c14df765fd78508db6539b6124e3/__tests__/utils/typedData.test.ts#L50

**Expected behavior**
All preset types are encoded as objects:
```
"Example"("n0":"TokenAmount","n1":"NftId")"NftId"("collection_address":"ContractAddress","token_id":"u256")"TokenAmount"("token_address":"ContractAddress","amount":"u256")"u256"("low":"u128","high":"u128")
```
**Actual behavior**
All preset types are encoded as basic types:
```
"Example"("n0":"TokenAmount","n1":"NftId")
```

**Desktop (please complete the following information):**

- Starknet.js version cb2059039e3b42501cdfefec7802da83eb73645b

**Comment by penovicp** [comment]
Note that in the current code, following the SNIP notation, **encode_type** is treated as a simple type but **encoding** is applied as for a custom type/object.

@sgc-code Could you confirm that **encode_type** should be applied the same as for a custom type? I recall being conflicted about this while working on #920 since either approach is essentially a constant but it seems I didn't remember to explicitly ask about it.
