### ISSUE TITLE
`encodeValue` of typed data unable to handle negative `i128` values

### ISSUE THREAD

**Issue by DelevoXDG** [starknet-io/starknet.js#1004]
**Describe the bug**
Correct me if I'm wrong, but from what I understand, the purpose of signed `i128`, [introduced](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md#when-x-is-a-i128) in SNIP-12, is to support both positive and negative values. Currently, `i128` is handled just like any other unsigned value, which leads to errors when negative `i128` value is encountered: https://github.com/starknet-io/starknet.js/blob/6cd35aa26d47d4f3a594349d65792fd1f368ba67/src/utils/typedData.ts#L318

Afaiu, negative `i128` values should be supported and [transformed to felt values](https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/serialization_of_Cairo_types/#data_types_of_252_bits_or_less).

**To Reproduce**
Modify [base types example](https://github.com/starknet-io/starknet.js/blob/develop/__mocks__/typedData/example_baseTypes.json) to include `i128` value:
```json
{
    "types": {
        "StarknetDomain": [
            { "name": "name", "type": "shortstring" },
            { "name": "version", "type": "shortstring" },
            { "name": "chainId", "type": "shortstring" },
            { "name": "revision", "type": "shortstring" }
        ],
        "Example": [
            { "name": "n0", "type": "felt" },
            { "name": "n1", "type": "bool" },
            { "name": "n2", "type": "string" },
            { "name": "n3", "type": "selector" },
            { "name": "n4", "type": "u128" },
            { "name": "n5", "type": "i128" },
            { "name": "n6", "type": "ContractAddress" },
            { "name": "n7", "type": "ClassHash" },
            { "name": "n8", "type": "timestamp" },
            { "name": "n9", "type": "shortstring" }
        ]
    },
    "primaryType": "Example",
    "domain": {
        "name": "StarkNet Mail",
        "version": "1",
        "chainId": "1",
        "revision": "1"
    },
    "message": {
        "n0": "0x3e8",
        "n1": true,
        "n2": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "n3": "transfer",
        "n4": "0x3e8",
        "n5": -1000,
        "n6": "0x3e8",
        "n7": "0x3e8",
        "n8": 1000,
        "n9": "transfer"
    }
}
```
Run:
```
structHash = getStructHash(
      exampleBaseTypes.types,
      'Example',
      exampleBaseTypes.message,
      TypedDataRevision.Active
    );
```

**Expected behavior**
The hash is calculated successfully

**Actual behavior**
```
SyntaxError: Cannot convert 0x-3e8 to a BigInt
```

**Desktop (please complete the following information):**

- Starknet.js version fdcc7fbf5957c14df765fd78508db6539b6124e3

**Additional context**

**Comment by penovicp** [comment]
You are right. Thanks for reporting this!
