### ISSUE TITLE
refactor various `typeof` comparisons with util methods

### ISSUE THREAD

**Issue by ivpavici** [starknet-io/starknet.js#1006]
**Is your feature request related to a problem? Please describe.**
There are instances of `typeof` comparisons in code that could be refactored, and magic strings removed

An example:
https://github.com/starknet-io/starknet.js/blob/880b906f09839871f0a08a737620d4d8107f0d81/src/utils/provider.ts#L116

...which could be replaced by https://github.com/starknet-io/starknet.js/blob/880b906f09839871f0a08a737620d4d8107f0d81/src/utils/num.ts#L28

There are more similar instances in the code

**Describe the solution you'd like**
I would like to see other similar instances refactored if possible, possibly expanding `utils` with more methods

For example, adding a  `isNumber` helper method

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by ktarun1419** [comment]
Hello, @ivpavici , may I take on this issue?

**Comment by ivpavici** [comment]
hey @ktarun1419 ! Sorry, I got contacted yesterday regarding this a bit earlier and there is a PR already... 
But don't worry, there will be more issues! If you see something that can be improved feel free to open an issue and subsequent PR also! it can also qualify for OD rewards
