### ISSUE TITLE
Improve onboarding process for the new contributors

### ISSUE THREAD

**Issue by tabaktoni** [starknet-io/starknet.js#1008]
**Is your feature request related to a problem? Please describe.**

1. New contributors flow is reading the contribution guide, forking/fetching the repo, and then running tests. Without downloading and running devnet this error message will pop up:
```ts
Error: Jest: Got error running globalSetup - /Users/tabaktoni/Work/starknet.js/__tests__/config/jestGlobalSetup.ts, reason: Setting Account using all known strategies failed, provide basic test parameters
```
This means auto-setup is unable to configure default env params aka. no local devnet is running on port 5050

**Describe the solution you'd like**
Improve the process so that new contributors can frictionlessly run the tests.
The suggested solution is to alter the messaging suggesting devs download & run [starknet-devnet-rs latest docker image](https://hub.docker.com/r/shardlabs/starknet-devnet-rs/tags) and run on port 5050
``docker run -p 5050:5050 shardlabs/starknet-devnet-rs:latest``
[starknet-devnet-rs Repo](https://github.com/0xSpaceShard/starknet-devnet-rs)

Improve the contribution guide readme.

**Describe alternatives you've considered**
Propose an additional improvement to this process in the form of the issue.

**Additional context**
The final goal is to have a simple process for new contributors' onboarding with all required resources available.
Remove the necessity for core devs to support new contributors.

**Comment by lukasaric** [comment]
@tabaktoni  I can take this one, if that's ok :)
