### ISSUE TITLE
Add support for uint512

### ISSUE THREAD

**Issue by tabaktoni** [starknet-io/starknet.js#1013]
**Is your feature request related to a problem? Please describe.**
Add support for uint512 the same way we support uint256
https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/serialization_of_Cairo_types/#serialization_in_u512_values

**Describe the solution you'd like**

- Create singular class CairoUint512
https://github.com/starknet-io/starknet.js/blob/feat/wallet-rpc/src/utils/cairoDataTypes/uint256.ts#L39

- Implement request and response parsers using it

**Comment by PhilippeR26** [comment]
@ivpavici 
I can handle this one.

**Comment by PhilippeR26** [comment]
@tabaktoni 
For those used to using `cairo.uint256()` (like me), I plan to create also a `cairo.uint512()`
