### ISSUE TITLE
Add tests for Cairo types

### ISSUE THREAD

**Issue by ivpavici** [starknet-io/starknet.js#1026]
**Is your feature request related to a problem? Please describe.**
We do not have any specific tests for Cairo types other than the one @tabaktoni created modeling schema for it on `uint256`. 

**Describe the solution you'd like**
We need to add all tests for Cairo types and convert them.
It is possible there are some tests around utils or contract testing but they should be extracted, and a singular test for CairoFelt should be created here:
https://github.com/starknet-io/starknet.js/tree/next-version/__tests__/utils/CairoTypes

**Describe alternatives you've considered**

**Additional context**

**Comment by ikrcatov** [comment]
@ivpavici can i take it?

**Comment by tabaktoni** [comment]
In general, this is a huge task we need to list all Cairo types that need to be converted.
maybe start by creating PR for dedicated CairoFelt tests ?
