### ISSUE TITLE
`toHex`truncates leading zeroes

### ISSUE THREAD

**Issue by naorye** [starknet-io/starknet.js#1028]
`toHex` function truncates leading zeroes:

https://github.com/starknet-io/starknet.js/blob/70e7ba68048540e91c4d65c03abfc1c1aa528600/src/utils/num.ts#L36

For example:
```
toHex('0x023A2aAc5d0fa69E3243994672822BA43E34E5C9') // === "0x23A2aAc5d0fa69E3243994672822BA43E34E5C9"
```
(zero after '0x' gets truncate)

**Comment by PhilippeR26** [comment]
Hello,
Seems to be a normal behavior...
If you want a leading 0 (if necessary) : 
```typescript
const hexNum = encode.sanitizeHex(hexString);
```

**Comment by PhilippeR26** [comment]
Just use `addAddressPadding(address: BigNumberish): string`

**Comment by ivpavici** [comment]
We have 3 options:
1. add additional explanations to the guides about this case
2. implement Toni's suggestion
3. do both :D

**Comment by PhilippeR26** [comment]
This function is already existing in Starknet.js :  https://www.starknetjs.com/docs/next/api/modules/#addaddresspadding

If you want, I can add some JSdoc.

**Comment by PhilippeR26** [comment]
Made.

**Comment by naorye** [comment]
@PhilippeR26 @ivpavici @tabaktoni 

Sorry, I didn't explain the actual issue.

The following method https://github.com/starknet-io/starknet.js/blob/d72b1bed805691b0914a24b23a3caab728ac6c0d/src/provider/rpc.ts#L675 uses `toHex` in order to make sure address is hex. By doing so padding zeroes are getting removed and the RPC throws an exception about incorrect address length.

**Comment by PhilippeR26** [comment]
This time I understood.
The node is expecting a string representing an hex number coded with 20 bytes.
I will have a look.
@ivpavici , could you assign me?

**Comment by PhilippeR26** [comment]
The test suite is performing a test of `provider.estimateMessageFee()` using a Cairo 0 contract. In this case it works without an Eth address coded in 20 bytes.
But if tested with a Cairo 1 contract, it fails!
So, I will propose a small PR.
