### ISSUE TITLE
signTransaction missing abi arg in Signer class

### ISSUE THREAD

**Issue by stanleyyconsensys** [starknet-io/starknet.js#1030]
**Describe the bug**

In Account class, the execute method will ask the signer to sign the transaction via signTransaction

it pass in transactions, signerDetails, abis

however in Signer Class, signTransaction method only contains 2 args

in https://github.com/starknet-io/starknet.js/blob/v6.6.0/src/signer/default.ts#L46

**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker]
- Node version : 18.18.2
- Starknet.js version: 6.60
- Network [devnet, testnet]: testnet

**Comment by dhruvkelawala** [comment]
But we don't need abis on starknet. So it's optional. We can remove it at this point. I don't think it solves any purpose

**Comment by stanleyyconsensys** [comment]
i agree, can we remove the abi from all interface for signTransaction?

**Comment by PhilippeR26** [comment]
I think that we can remove it from the Signer interface, but we have to keep it as parameter in `account.execute()`  to not create a breaking change.

**Comment by PhilippeR26** [comment]
If agreed this way, I have a PR to propose.

**Comment by ivpavici** [comment]
@tabaktoni a breaking PR could still be done now since v6 is not officially released?

**Comment by PhilippeR26** [comment]
The syntax
```typescript
const res = await account.execute(myCall, undefined, { maxFee: 1 * 10 ** 15 });
```
is very common.
I think we should not break it.

**Comment by penovicp** [comment]
I think we should defer to Phil's perspective on this.

A thing that could be done is that the method could be refactored to allow for truncated parameters (`execute(calls, details)`) together with the current notation (`execute(calls, abis, details)`) and mark it for future deprecation.

**Comment by tabaktoni** [comment]
So let's remove it from the signer and overload execute
