### ISSUE TITLE
Add JSDocs to all functions that miss them

### ISSUE THREAD

**Issue by ivpavici** [starknet-io/starknet.js#1033]
One example is `utils/address.ts`

There are more to find and add!

**Comment by ikrcatov** [comment]
Can i take it?

**Comment by raizo07** [comment]
Hello @ivpavici. I'd like to be assigned to this if it is still open? I should get it done under a day.

**Comment by ivpavici** [comment]
@raizo07 sorry @ikrcatov got assigned earlier! 

but feel free to find and add any missing docs regardless!
