### ISSUE TITLE
error Failed to deserialize param when estimateFee

### ISSUE THREAD

**Issue by mianshenglee** [starknet-io/starknet.js#1041]
**Describe the bug**
call contract function(swap function), and got this error:

starknet_estimateFee with params 
{
    "request": [
        {
            "type": "INVOKE",
            "sender_address": "0x036172525b112dc701b6ce87d7b891a307f7654b1c755604de9353041a52e474",
            "calldata": [
                "0x1",
                "0x4505a9f06f2bd639b6601f37a4dc0908bb70e8e0e0c34b1220827d64f4fc066",
                "0x15543c3708653cda9d418b4ccd3be11368e40636c10c44b18cfe756b6d88b29",
                "0x9",
                "0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d",
                "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7",
                "0x20c49ba5e353f80000000000000000",
                "0x3e8",
                "0x0",
                "0x61b321b6655c1ca3038b522990396ee",
                "0x0",
                "0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d",
                "0x1bc16d674ec80000"
            ],
            "version": "0x100000000000000000000000000000001",
            "signature": [
                "0x49a3d65f2574025521124513afba26e754568999ab0798b8d7926724f73dd2c",
                "0x3908ea85368c0d6ae5cbbe698fbce42c4cd2463c6295c87a9a547702a75374b"
            ],
            "nonce": "0x6",
            "max_fee": "0x0"
        }
    ],
    "block_id": "pending"
}

 40: Contract error: {"revert_error":"Execution error at transaction index 0: Error in the called contract (0x036172525b112dc701b6ce87d7b891a307f7654b1c755604de9353041a52e474):
 Error at pc=0:20259:
 Got an exception while executing a hint: Execution failed. Failure reason: 0x4661696c656420746f20646573657269616c697a6520706172616d202331 ('Failed to deserialize param #1').
 Cairo traceback (most recent call last):
 Unknown location (pc=0:309)
 Unknown location (pc=0:5819)
 Unknown location (pc=0:11008)
 Error in the called contract (0x04505a9f06f2bd639b6601f37a4dc0908bb70e8e0e0c34b1220827d64f4fc066):
 Execution failed. Failure reason: 0x4661696c656420746f20646573657269616c697a6520706172616d202331 ('Failed to deserialize param #1').
 "}

**Comment by PhilippeR26** [comment]
Hello,
We need more context, to be able to reproduce this error.

**Comment by tabaktoni** [comment]
Missing reproduction steps.
If you still encounter this issue, please provide a full bug description following the bug report template guidelines.
