### ISSUE TITLE
deployAccount Function Failure - LibraryError: RPC: starknet_estimateFee

### ISSUE THREAD

**Issue by TiyoSheng** [starknet-io/starknet.js#1047]
Encountered an execution failure when trying to deploy an account using the deployAccount method. The error message is as follows:
<img width="672" alt="image" src="https://github.com/starknet-io/starknet.js/assets/17961751/31f64c65-78db-4635-a7f3-275339f06336">
<img width="742" alt="image" src="https://github.com/starknet-io/starknet.js/assets/17961751/accf7eb0-41bd-4227-a330-82e097b3989e">

Here is my code

<img width="504" alt="image" src="https://github.com/starknet-io/starknet.js/assets/17961751/d4eba4e6-58df-4fab-af5e-f930cf09388d">

**Comment by ivpavici** [comment]
you are missing some steps as far as I see, namely funding the address before deploying the account. Please take a close look at these guides:
https://www.starknetjs.com/docs/guides/create_account

**Comment by TiyoSheng** [comment]
> you are missing some steps as far as I see, namely funding the address before deploying the account. Please take a close look at these guides:
> 
> https://www.starknetjs.com/docs/guides/create_account

my network use --disable-fee
and starknet.js v5.23 is success
