### ISSUE TITLE
Updating documentation for deprecated features

### ISSUE THREAD

**Issue by SamrendraS** [starknet-io/starknet.js#1055]
**Bug Description**
Certain sections within the "Guides" segment are utilizing deprecated APIs, although some have been updated in the subsequent version of the documentation.

Specifically, I've observed missing details in the following areas:

1. **Connect Network, Connect Account, Connect Contract**: These sections still rely on Provider.
2. **Create Account**: The Argent Account Class Hash currently refers to a Cairo 0 account, but it can now be updated to a Cairo 2 account Class Hash.

**Expected Behavior**
An update to the guides is expected to enhance the user experience in adopting Starknet.js and developing applications with it.

**Additional Context**
If these documentation choices are maintained in the current version by design, please inform me or close the issue accordingly.  Additionally, any other missing or outdated pieces in the documentation can be added to this issue for resolution.

**Comment by fishonamos** [comment]
Hi @SamrendraS . I can handle this.

**Comment by SamrendraS** [comment]
Hi, I'm actually waiting for someone from the Starknet.js team to confirm if the changes are needed. 

I intend to pick the issue up post that.

**Comment by PhilippeR26** [comment]
Hello,
Most of your comments are already implemented in guides of V6, or ready in the next-version branch.

**Comment by SamrendraS** [comment]
Hi Philippe,
Thanks for letting me know, the issue can be closed in case the changes aren't needed.
 
Is there a reason that the current (non next) versions are using the older syntax, as intellisense actively marks them as deprecated.

**Comment by PhilippeR26** [comment]
current version of doc is an old v5.24.3 version. The new V6 doc is ready, but not yet released.

**Comment by SamrendraS** [comment]
Perfect, thanks. I'll be closing this issue.
