### ISSUE TITLE
Update RPC to 0.7.1

### ISSUE THREAD

**Issue by ivpavici** [starknet-io/starknet.js#1069]
The spec:

https://github.com/starkware-libs/starknet-specs/compare/v0.7.0...v0.7.1

**Comment by Oshioke-Salaki** [comment]
Please can i handle this?

**Comment by ivpavici** [comment]
@Oshioke-Salaki could you do it till tomorrow?

**Comment by Oshioke-Salaki** [comment]
You mean you want it done before tomorrow?

**Comment by ivpavici** [comment]
we meant on developing this today or tomorrow latest - could you do it by tomorrow EOD?

**Comment by Oshioke-Salaki** [comment]
Yes i can

**Comment by ivpavici** [comment]
@Oshioke-Salaki ups, sorry, seems like the PR is already made... 
Please take a look at some others, I will gladly assign you! And they will not have such a tight schedule

**Comment by ivpavici** [comment]
@Oshioke-Salaki do you want to take a look and update these schemas to the latest RPC ?
https://github.com/starknet-io/starknet.js/tree/develop/__tests__/schemas

**Comment by Oshioke-Salaki** [comment]
okay no problem. i can handle that

**Comment by ivpavici** [comment]
please add comment on #1072

**Comment by Oshioke-Salaki** [comment]
Done sir
