### ISSUE TITLE
Refactor test's response schema validation

### ISSUE THREAD

**Issue by tabaktoni** [starknet-io/starknet.js#1072]
**What result I would like to achieve**
Add:
` __tests__/schemas/rpc/*` - it should be possible to generate JSON validation schema from [ JSON RPC Spec](https://github.com/starkware-libs/starknet-specs)
`__tests__/schemas/account.json `- account specific responses (for those same as RPC add ref to rpc spec)
`__tests__/schemas/contract.json` - contract specific (for those same as RPC add ref to rpc spec)
`__tests__/schemas/provider.json` - provider specific (for those same as RPC add ref to rpc spec), diff. ones are those having returned response parser)

Remove:
`__tests__/schemas/sequencer.json ` 

Resolve:
`__tests__/schemas/lib.json `
`__tests__/schemas/component.json `
These two can stay or be removed depending on requirements during refactoring.
components.json should probably be part of schemas/rpc/* and lib should contain only lib specific definitions.

**Describe the solution you'd like**
In theory, we should be able to regenerate ` __tests__/schemas/rpc/*`from [ JSON RPC Spec](https://github.com/starkware-libs/starknet-specs) so it would be nice to have a script to do it for future versions.

**Describe alternatives you've considered**
Instead of auto conversion from RPC Spec 0.7.1 manually convert to JSON validation schema.

**Additional context**
Use the latest Spec version [ JSON RPC Spec](https://github.com/starkware-libs/starknet-specs/tree/v0.7.1)
at the moment it is tag v0.7.1

**Comment by Oshioke-Salaki** [comment]
Please I would want to work on this.

**Comment by ivpavici** [comment]
@princeibs sorry, we agreed a bit earlier with @Oshioke-Salaki [here ](https://github.com/starknet-io/starknet.js/issues/1069#issuecomment-2047363550) to take this issue

**Comment by Oshioke-Salaki** [comment]
Hello please is there a way i can contact you, if i have questions?

**Comment by ivpavici** [comment]
feel free to post here!

**Comment by ivpavici** [comment]
unassigned due to being stale and will be offered to participants of the ODHack event

**Comment by Ugo-X** [comment]
hello @tabaktoni and @ivpavici please can i be assigned this task?

**Comment by fmmesen** [comment]
Hi! @ivpavici I'm comming from ODHack, I'd like to work on this task, Could I be assigned to it?
Thank you!

**Comment by fmmesen** [comment]
I had doubts about this "In theory, we should be able to regenerate  __tests__/schemas/rpc/*from [JSON RPC Spec](https://github.com/starkware-libs/starknet-specs) so it would be nice to have a script to do it for future versions."
Is the completion of this script expected as part of this pull request?
