### ISSUE TITLE
Replace ENUM with companion pattern approach

### ISSUE THREAD

**Issue by lukasaric** [starknet-io/starknet.js#1077]
**Is your feature request related to a problem? Please describe.**
Currenlty,  TS `enum` is used across the codebase. I would be good to be replaced with the `companion pattern` approach to increase the type safety.
To have better understanding, here's a good thread why it would be good to avoid enums in TS
[Don't use Enums in Typescript, they are very dangerous](https://dev.to/ivanzm123/dont-use-enums-in-typescript-they-are-very-dangerous-57bh#:~:text=Excessive%20use%20of%20regular%20ENUMs,new%20values%20can%20be%20added.)

**Describe the solution you'd like**
BEFORE
```ts
export enum NetworkName {
  SN_MAIN = 'SN_MAIN',
  SN_GOERLI = 'SN_GOERLI',
  SN_SEPOLIA = 'SN_SEPOLIA',
}
```
AFTER
```ts
export const NetworkName = {
  SN_MAIN: 'SN_MAIN',
  SN_GOERLI: 'SN_GOERLI',
  SN_SEPOLIA: 'SN_SEPOLIA',
} as const;

// eslint-disable-next-line @typescript-eslint/no-redeclare -- intentionally naming the variable the same as the type
export type NetworkName = (typeof NetworkName)[keyof typeof NetworkName];
```

**Describe alternatives you've considered**
Pros:
- Increased type safety
- Less prone to mistakes and errors (especially for numerics)
- Decreased output size and improved performance

Cons:
- Eslint `re-declare` rule does not have exception for declaring the same name type and variable. Either, the rule should be disabled or we'll add eslint ignore for these cases which will be annoying

**Additional context**

**Comment by ivpavici** [comment]
@kateberryd sorry, Luka reached out earlier to solve this (when he opened the issue), but I forgot to assign him... 
Keep an eye on other issues, there will soon be more!
