### ISSUE TITLE
Theme styling issue on search results

### ISSUE THREAD

**Issue by bhavyagosai** [starknet-io/starknet.js#1079]
**Describe the bug**
- The list of results displayed when one searches using the search button gets colors messed up when hovering on an item.

- The background becomes white but the text color itself does not change to black (or any designated contrasting hex) and stays white thus making the list item unreadable when hovered.

- This particular thing happens only in dark mode of the website

I can fix this. Would you mind assigning it to me?

**To Reproduce**
1. make sure you are running the website in dark mode
2. just click on the search button, type a search string and wait for search results to generate.
3. hover on the search results

**Expected behavior**
- Text color should accordingly change too.

**Screenshots**

<img width="1429" alt="image" src="https://github.com/starknet-io/starknet.js/assets/64588227/e5e46b52-1785-4c7e-a0bf-08e64c2c387c">

**Desktop**

- Browser & version: Brave 1.64.116
- Node version 21.5.0
- Starknet.js version: 5.24.3
- Network: NA

**Comment by bhavyagosai** [comment]
@ivpavici ik its smol but can you take a look? 😬

**Comment by ivpavici** [comment]
thanks!
