### ISSUE TITLE
Airdrop allocation

### ISSUE THREAD

**Issue by mathaszip** [starknet-io/starknet.js#1084]
Hey there,

I wanted to bring to your attention an issue that was raised back in February on the [provisions-data](https://github.com/starknet-io/provisions-data) GitHub page. It pertains to users who have met the airdrop criteria but haven't received anything. Despite my efforts to communicate this to the developers, I was inexplicably banned from Discord some time ago. Undeterred, I'm reaching out here in hopes of raising awareness, as it appears this matter has been overlooked.

Within my post, you'll find accounts from several individuals affected by this issue.

Best regards,
Mathias

**Comment by penovicp** [comment]
This space is only for technical discussions for `starknet.js`. None of the decision makers from the Starknet Foundation are active on this repository so voicing grievances here won't reach them. If Discord is not an option, other social media such as Twitter/X or Telegram are better avenues for such feedback.
