### ISSUE TITLE
Add link to Discord in all relevant places

### ISSUE THREAD

**Issue by ivpavici** [starknet-io/starknet.js#1085]
Link to Discord Starknet.js channel:
https://discord.com/channels/793094838509764618/927918707613786162

Need to add it in a couple of places:
1. https://github.com/starknet-io/starknet.js/blob/main/CONTRIBUTING.md#need-help
2. https://github.com/starknet-io/starknet.js?tab=readme-ov-file#%EF%B8%8F-contributing
3. https://www.starknetjs.com/ under the community part
![image](https://github.com/starknet-io/starknet.js/assets/2848732/26a8f448-879a-4775-8eff-fc2f59cdba76)

**Comment by princeibs** [comment]
I would like to hop on the issue when the event starts

**Comment by hemantwasthere** [comment]
Hey @ivpavici, Would love to work on this issue

**Comment by ivpavici** [comment]
@hemantwasthere thanks but this was supposed to be offered to participants of ODHack event starting in 4 days...

**Comment by Ugo-X** [comment]
> @hemantwasthere thanks but this was supposed to be offered to participants of ODHack event starting in 4 days... https://onlydust.notion.site/ODHack-Common-Guidelines-b9c6b6a4ac4146d087185568aca38a3f

Hello Good morning @ivpavici, My name is Ugo, it's Monday😁, I would please love if i can be assigned to this task, thank you

**Comment by PabloVillaplana** [comment]
Hello @ivpavici I would love to be part of this effort! 👷🏽‍♂️, thanks (I am in OD Hack telegram, ready to start on Monday 🫡)

**Comment by ivpavici** [comment]
hey everyone, as per the guidelines, it would be fair to assign this issue to the first person who applied today... that would be @Ugo-X 
But the PR is already open on this one, so I will remove this one from the hack... please take a look at this issue, it can have multiple people working on it, and should be straightforward
https://github.com/starknet-io/starknet.js/issues/1090

**Comment by hemantwasthere** [comment]
Hey @ivpavici, do we have a telegram group of starknet.js community

**Comment by ivpavici** [comment]
no, not a dedicated one
