### ISSUE TITLE
Run type coverage, compile a detailed report and fix what is possible to fix

### ISSUE THREAD

**Issue by ivpavici** [starknet-io/starknet.js#1088]
https://dev.to/mbarzeev/get-your-typescript-coverage-report-5c5p

**Comment by bhavyagosai** [comment]
hey, i would like to work on this. would you mind assigning this to me? or it will be assigned when ODHack gets started?

**Comment by fishonamos** [comment]
@ivpavici . I will love to work on this!

**Comment by saimeunt** [comment]
@ivpavici Hey I'd like to work on this one!

I will carefully read the blog post to get familiar with `typescript-coverage-report` and add it to starknet.js to try to fix the maximum TS errors.

**Comment by ivpavici** [comment]
@bhavyagosai as per the guidelines, it will be fair to assign @saimeunt since this morning is the beginning of the Hack.
If in the next 2-3 days there is no progress I will assign you!

**Comment by ivpavici** [comment]
@bhavyagosai also please TAL at this issue:
 https://github.com/starknet-io/starknet.js/issues/1090
