### ISSUE TITLE
Add test code coverage step in Github actions

### ISSUE THREAD

**Issue by ivpavici** [starknet-io/starknet.js#1089]
https://about.codecov.io/blog/measuring-typescript-code-coverage-with-jest-and-github-actions/

The idea is:

- a dev can run locally a command to see the code coverage of tests
- the same thing can be run on all PR-s on the CI in github

**Comment by jaipaljadeja** [comment]
Hey, is it up for grabs? i would like to take this : )

**Comment by ivpavici** [comment]
hi!
On 22nd when ODHack starts!
https://onlydust.notion.site/ODHack-Common-Guidelines-b9c6b6a4ac4146d087185568aca38a3f

**Comment by jaipaljadeja** [comment]
> hi! On 22nd when ODHack starts! https://onlydust.notion.site/ODHack-Common-Guidelines-b9c6b6a4ac4146d087185568aca38a3f

Understandable 🫡

**Comment by Jemiiah** [comment]
@ivpavici can i be assigned this work?

**Comment by ivpavici** [comment]
Hi @Jemiiah ! I see your profile is new, can you tell me more about yourself, and how you plan to tackle this issue?

If not, @jaipaljadeja can be assigned on this issue

**Comment by Ugo-X** [comment]
Hello @Jemiiah please can i be assigned this task, it's something I'd really love to do

**Comment by Jemiiah** [comment]
Sureee @Ugo-X

**Comment by Ugo-X** [comment]
> Sureee @Ugo-X

alright @ivpavici please can I work on this, I'd really love to work on this. Gracias!

**Comment by ivpavici** [comment]
@Ugo-X we can assign only one person per task, do you want this one or the other you got assigned?

**Comment by Ugo-X** [comment]
> @Ugo-X we can assign only one person per task, do you want this one or the other you got assigned?

ohh, Okay please can I be assigned this instead, let me work on this swiftly and maybe later if the other one is still available I can still apply. Thank you @ivpavici

**Comment by Ugo-X** [comment]
hi @ivpavici 
I've been able to write the test coverage file but on execution with Github actions, it alerts to a dependency error about a missing module

<img width="1280" alt="Screenshot 2024-04-22 at 15 06 57" src="https://github.com/starknet-io/starknet.js/assets/133219527/6a78a9da-d4e4-4eaf-b378-fc6c343136c7">
so do i count the test coverage issue as closed and initiate a pull request or try working around fixing this current problem?

**Comment by Ugo-X** [comment]
> hi! feel free to make a PR and we can see... this error looks strange, we'll TAL

alright will do that right away
