### ISSUE TITLE
Bug parsing events when nested events involved

### ISSUE THREAD

**Issue by NikitaMishin** [starknet-io/starknet.js#1134]
**Location:** https://github.com/starknet-io/starknet.js/blob/66a5c0341eccfef0dcdf1312c15627b7d4f6b675/src/utils/events/index.ts#L52C21-L52C28

Encounter issue with parsing events emitted by components:

**Sample of code** (just take any events that emitted in nested components):
```
    const eventsC = provider.getEvents(....)
    const abiEvents = STARKNETJS.events.getAbiEvents(abi);
    const abiStructs =  STARKNETJS.CallData.getAbiStruct(abi);
    const abiEnums = STARKNETJS.CallData.getAbiEnum(abi);
    let parsedEvents = STARKNETJS.events.parseEvents(eventsC.events, abiEvents, abiStructs, abiEnums)
    console.log(parsedEvents)

```
produces 0 parsed events

**Reason:** AbiEvents not handle correctly case for nested events when they defined by extra key that associated with component. In my particular case second key was the correct one to do lookup to abiEvents
**Potential solution**: 

```
let abiEvent: EventAbi | undefined;

// Loop through all keys and find the first matching event
for (const key of recEvent.keys) {
    abiEvent = abiEvents[key];
    if (abiEvent) {
        break; // Exit the loop once a match is found
    }
}
```
iterate over all keys/or first N instead of just first one. I presume there should be no collisions

**Comment by MartinXV111** [comment]
can i hop on this?

**Comment by martinvibes** [comment]
hi @NikitaMishin can i hop on this

**Comment by NikitaMishin** [comment]
also  if several components have same name for event  getAbiEvents would just shallow rewrite it,
 not taking into account component hash

**Comment by od-hunter** [comment]
Hello @NikitaMishin please assign me to this project. This is my first time contributing to Starknet ecosystem and would love to proof my acquired skills, thank you.

**Comment by od-hunter** [comment]
Hello @NikitaMishin im ready for work assign me please.

**Comment by od-hunter** [comment]
@NikitaMishin still waiting for your go ahead.

**Comment by Timilehin-bello** [comment]
@NikitaMishin please can you kindly assign this task to me. I'll start working on it and revert

**Comment by PhilippeR26** [comment]
Hello @NikitaMishin ,
I would like to repeat completely your problem. I need the network used, the parameters in getEvents, the address of the contract of these events.

**Comment by PhilippeR26** [comment]
What's the content of `restKeys`?

**Comment by PhilippeR26** [comment]
The first key is `0x22ea134d4126804c60797e633195f8c9aa5fd6d1567e299f4961d0e96f373ee`. I suppose that it's a starknetKeccak of some text. Do you know which text is it?

**Comment by PhilippeR26** [comment]
Seems to be the hash of `BalancerEvent`

**Comment by PhilippeR26** [comment]
OK, I have now a good understanding of this problem.
I will use a nested `findIndex / includes ` to find the right key.

**Comment by NikitaMishin** [comment]
> also if several components have same name for event getAbiEvents would just shallow rewrite it, not taking into account component hash

@PhilippeR26, this issue is related. I assume getAbiEvents does not take the component hash into account. If two events have the same base name, it will overwrite one with the other. For example, I defined similar events with the same name "Deposit" in two components, and it resulted in an incorrect ABI, only recognizing one of the events instead of both.

**Comment by PhilippeR26** [comment]
I think it's a good guideline to not have 2 times the same name in an abi. Otherwise you are going straight to problems.

**Comment by NikitaMishin** [comment]
> I think it's a good guideline to not have 2 times the same name in an abi. Otherwise you are going straight to problems. Is it possible to have events nested 2 times (use of a Cairo component that uses a sub-component that emits events)?

Yes, possible:
https://github.com/LayerAkira/kurosawa_akira/blob/53e50c3e776fe352dcdc8160d1666d7a3628690a/src/DepositComponent.cairo#L23
https://github.com/LayerAkira/kurosawa_akira/blob/53e50c3e776fe352dcdc8160d1666d7a3628690a/src/RouterComponent.cairo#L88

**Comment by PhilippeR26** [comment]
My question was : is it possible to use in Cairo a component in a component?

**Comment by NikitaMishin** [comment]
> My question was : is it possible to use in Cairo a component in a component?

yes in a sense that you can interact with other components in component

**Comment by PhilippeR26** [comment]
🥴 I don't know how to ask my question in an understandable way  ... 
Let's try an other way :
At the end, is it possible to have an event with a key array including more than 2 hashes to define the event name?

**Comment by NikitaMishin** [comment]
> 🥴 I don't know how to ask my question in an understandable way ...
> Let's try an other way :
> At the end, is it possible to have an event with a key array including more than 2 hashes to define the event name?

oh, this one i dont know tbh i think not possible

**Comment by PhilippeR26** [comment]
Hello, 
I coded something that is recursive and can handle several levels of components (even if it's maybe not possible today).
Could you try with this line in your `package.json`? :
```
"starknet": "philippeR26/starknet.js#c9fab45b78222154247d8078bb60af2dd30a9611",
```
Now, the result contains the full name of the event (was just the last word), to differentiate the events with the same name.
Waiting your response.

**Comment by NikitaMishin** [comment]
> Hello, I coded something that is recursive and can handle several levels of components (even if it's maybe not possible today). Could you try with this line in your `package.json`? :
> 
> ```
> "starknet": "philippeR26/starknet.js#c9fab45b78222154247d8078bb60af2dd30a9611",
> ```
> 
> Now, the result contains the full name of the event (was just the last word), to differentiate the events with the same name. Waiting your response.

ok, ill try in a tad later today, thanks!

**Comment by PhilippeR26** [comment]
For the test suite of Starknet.js, could you provide me a link in Sepolia for an example these events :
- kurosawa_akira::DepositComponent::deposit_component::Deposit
- kurosawa_akira::RouterComponent::router_component::Deposit

**Comment by NikitaMishin** [comment]
> Hello, I coded something that is recursive and can handle several levels of components (even if it's maybe not possible today). Could you try with this line in your `package.json`? :
> 
> ```
> "starknet": "philippeR26/starknet.js#c9fab45b78222154247d8078bb60af2dd30a9611",
> ```
> 
> Now, the result contains the full name of the event (was just the last word), to differentiate the events with the same name. Waiting your response.

yeap works

**Comment by PhilippeR26** [comment]
> For the test suite of Starknet.js, could you provide me a link in Sepolia for an example these events :
> 
>     * kurosawa_akira::DepositComponent::deposit_component::Deposit
> 
>     * kurosawa_akira::RouterComponent::router_component::Deposit

Do you have also in your code an example of a nested  event tagged `#[flat]``?

**Comment by NikitaMishin** [comment]
> > For the test suite of Starknet.js, could you provide me a link in Sepolia for an example these events :
> > ```
> > * kurosawa_akira::DepositComponent::deposit_component::Deposit
> > 
> > * kurosawa_akira::RouterComponent::router_component::Deposit
> > ```
> 
> Do you have also in your code an example of a nested event tagged `#[flat]`?
i didn't use #flat tbh seems like still not prod ready given some old discussions in cairo group.
deposit event: https://sepolia.voyager.online/event/70352_34_3
router deposit event: https://sepolia.voyager.online/event/70352_29_3

they are on same block

**Comment by PhilippeR26** [comment]
Found some `[#flat]` in OpenZeppelin contracts. I have found a corresponding event.
So, I finalize and clean my code. then, I will propose quickly a PR.

**Comment by NikitaMishin** [comment]
> Found some `[#flat]` in OpenZeppelin contracts. I have found a corresponding event. So, I finalize and clean my code. then, I will propose quickly a PR.

top! very quick, thanks!
