### ISSUE TITLE
Impossible to use computeHintedClassHash hash function

### ISSUE THREAD

**Issue by PhilippeR26** [starknet-io/starknet.js#1135]
**Describe the bug**
In utils/hash, the `computeHintedClassHash()` function is set a default export :
https://github.com/starknet-io/starknet.js/blob/66a5c0341eccfef0dcdf1312c15627b7d4f6b675/src/utils/hash/classHash.ts#L115
As a Starknet.js library user, I am not able to import and use this function.
Error message :
```
TSError: ⨯ Unable to compile TypeScript:
src/tmp/26.testSepolia.ts:33:25 - error TS2551: Property 'computeHintedClassHash' does not exist on type 'typeof index$1'. Did you mean 'computeCompiledClassHash'?

33     const result = hash.computeHintedClassHash()
                           ~~~~~~~~~~~~~~~~~~~~~~
```

**To Reproduce**
In a ts-node script :
```typescript
import { hash } from "starknet";
const result = hash.computeHintedClassHash();
```

**Expected behavior**
To be able to use this function.

**Screenshots**
N/A
**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker] : any
- Node version [e.g. 16.0.1] : ts-node@10.9.2
- Starknet.js version :  v6.9.0
- Network [devnet, testnet]: any

**Additional context**

> [!WARNING]
> Currently not open to contributors.

**Comment by martinvibes** [comment]
@PhilippeR26  can i hop on this?

**Comment by PhilippeR26** [comment]
Not yet.
I am creating today several issues, that have to be first discussed internally.
The team will then decide if it will be solved internally or with contributors.

**Comment by tabaktoni** [comment]
FIx:
Add into starknet.js/src/utils/hash/index.ts
```ts
export { default as computeHintedClassHash } from './classHash';
```

But I don't think we need to have default export anyway, so just remove default, run test if all ok resolved.
