### ISSUE TITLE
provider.txIdentifier error when used with txId optional parameter

### ISSUE THREAD

**Issue by PhilippeR26** [starknet-io/starknet.js#1136]
**Describe the bug**
There is a `txIdentifier` function in utils/provider :
https://github.com/starknet-io/starknet.js/blob/66a5c0341eccfef0dcdf1312c15627b7d4f6b675/src/utils/provider.ts#L95-L101
I don't know what's exactly the purpose of this function, but if to try to use it with the parameter txId, an error occurs  :
```
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at Object.txIdentifier (/home/edmond/Documents/starknet/starknet.js-workshop-typescript/node_modules/starknet/src/utils/provider.ts:97:34)
```
Of course, you can't stringify a BigNumberish...

**To Reproduce**
```typescript
import { provider } from "starknet";
const result = provider.txIdentifier(undefined, 26n);
```
**Expected behavior**
No Error.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker] : any
- Node version [e.g. 16.0.1] ts-node": "^10.9.2
- Starknet.js version : v6.9.0
- Network [devnet, testnet] : any 

**Additional context**

> [!WARNING]
> Currently not open to contributors.

**Comment by abdulsalamIshaq** [comment]
I will like to be assigned to this @PhilippeR26

**Comment by abdulsalamIshaq** [comment]
Alright

**Comment by Jemiiah** [comment]
Okay will Iove to contribute to this project as well

**Comment by martinvibes** [comment]
can i hop on this one @PhilippeR26

**Comment by PhilippeR26** [comment]
Please read just above.

**Comment by Jemiiah** [comment]
@PhilippeR26 how would we know when this issue have been accepted to be contributed on
