### ISSUE TITLE
Starknet 0.6.10 Constants Access Issue on final package

### ISSUE THREAD

**Issue by tabaktoni** [starknet-io/starknet.js#1158]
**Describe the bug**
- constants don't expose StarknetChainId nor any other as const+type exports on the final build
- Local usage is working (from /src) in the tests.

The imminent conclusion is that namespaced as const+type exports don't get bundled properly.

**To Reproduce**
```ts
import { constants } from "starknet";
const a=constants.StarknetChainId.SN_SEPOLIA;
```

**Expected behavior**
Example should pass build

- Node version [e.g. 21.0.0]
- Starknet.js version 0.6.10

**Comment by jrmncos** [comment]
hey! I would like to tackle this one
