### ISSUE TITLE
Adding Ledger Signer support

### ISSUE THREAD

**Issue by amanusk** [starknet-io/starknet.js#1168]
**Is your feature request related to a problem? Please describe.**
Ledger now has a Starknet App, supporting singing transactions with Stark Curve on Ledger. Any existing Starknet account can now be used with Ledger as a signer. 

**Describe the solution you'd like**
Add a custom `LedgerSigner` to starknet.js

This can be part of a broader generic signer implementation, but provided as part of the SDK for simpler integration 

**Additional context**
Reference implementation on starknet-rs:

https://github.com/xJonathanLEI/starknet-rs/blob/db1fa598232f0698d942cc974f481b5d888ac080/starknet-signers/src/ledger.rs

**Comment by ivpavici** [comment]
relevant:
https://github.com/starknet-io/starknet.js/pull/748

**Comment by PhilippeR26** [comment]
@amanusk Is it a JS/TS equivalence to the rust library `coins-ledger`?

**Comment by PhilippeR26** [comment]
My (very) old Nano S is not compatible with the Starknet ledger APP.
So, I ordered a new Nano X, to test it.
![ledgerNanoX](https://github.com/starknet-io/starknet.js/assets/81040730/49ec600a-10e7-4ebc-b6dc-0d8d2d89209c)
Nice!

**Comment by PhilippeR26** [comment]
I can communicate with it :
```typescript
TransportNodeHid {
  exchangeTimeout: 30000,
  unresponsiveTimeout: 15000,
  deviceModel: {
    id: 'nanoX',
    productName: 'Ledger Nano X',
    productIdMM: 64,
    legacyUsbProductId: 4,
    usbOnly: false,
    memorySize: 2097152,
    masks: [ 855638016 ],
    getBlockSize: [Function: getBlockSize],
    bluetoothSpec: [ [Object] ]
  },
  ```
  I have not to dig to 
  - recover the pubkey
  - sign a hash (as the ledger APP is not able to build a transaction)

**Comment by PhilippeR26** [comment]
The job to perform is mainly to create code for these 2 red parts :
![LedgerArchitecture](https://github.com/starknet-io/starknet.js/assets/81040730/b5a5608b-5b09-417b-8752-ade05ccb221f)
for 3 methods :
- getVersion
- getPubKey
- sign

**Comment by PhilippeR26** [comment]
It was difficult, but it works.
The documentation is full of errors or missing data : https://github.com/LedgerHQ/app-starknet/blob/develop/docs/apdu.md
The current code works only in Node for a Ledger connected with USB. I have to see how to handle Web USB & Web Bluethooth...

**Comment by PhilippeR26** [comment]
Made with a Starknet.js Signer : 
![Capture d’écran du 2024-07-16 19-43-16](https://github.com/user-attachments/assets/c5af0628-2288-45c2-b034-98add78571a8)

**Comment by PhilippeR26** [comment]
Ledger Nano X is not accepted with a Bluetooth connection, in my Linux Mint (Chrome, Brave, FireFox).
I have no knowledge about React native; so I didn't tested in mobile.
So, it works in my config in Node script & in Web DAPP  (both connected with USB).

**Comment by PhilippeR26** [comment]
@ivpavici 
I will propose a PR for the corresponding Signer.
