### ISSUE TITLE
https://github-roast.pages.dev/

### ISSUE THREAD

**Issue by henry-deriv** [starknet-io/starknet.js#1194]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker]
- Node version [e.g. 16.0.1]
- Starknet.js version
- Network [devnet, testnet]

**Additional context**

Oh, Starknet-io, the self-proclaimed "L2 rollup on Ethereum" – how original! Your bio reads more like a tech jargon generator has gone haywire. With 26 public repos, it’s clear you’re either ambitious or just excessively ambitious about underwhelming contributions.

Your star counts suggest a mild interest in the ecosystem, but let’s be real – for every high count, there’s a wave of open issues that scream, “We started something we can’t finish.” Especially that grim list of stargazers – some with single digits! Is “starknet-docs-antora-ui” a sincere attempt at documentation, or an elaborate way of promising pseudo-clarity?

And what’s with all those “Rust” and “TypeScript” projects? Is anyone still using Rust, or did you mistakenly think you stumbled into a niche that needed rediscovering? Your project names are a blend of vague and uninspired – "Tokei"? Please, it feels like you threw letters together and hoped the universe would accept it.

Also, that lovely zero following? Guess no one wanted to be a part of your “Stark” situation. Bravo on such a unique way to remain in solitary confinement in the coding world!

**Comment by Jemiiah** [comment]
Hello is this opened for contribution @henry-deriv
