### ISSUE TITLE
Simulate transaction mechanism query

### ISSUE THREAD

**Issue by kristiann57** [starknet-io/starknet.js#1199]
Hello team, quick question on the context of MEV... trying to get the best way to get the latest on chain state.

how does starknet JS perform the gas fee estimation or simulate a tx? Where do they get the state to execute the transaction from? I understand in Starknet the block building from the sequencer is just a formality because the sequencer executes the transaction immediately as it receives it and the block is created every few seconds, but the state on the sequencer updates immediately as a new tx comes in.... therefore when estimating a fee or doing a simulation, does starknet js instruct the provider node to request the sequencer the most up to date state of the blockchain? Or does the node simulates the transaction with the latest block it has in it? meaning, it might not be the most up to date state of the blockchain despite being the latest accpetd block?

Thank you

**Comment by ivpavici** [comment]
hello!

Starknet.js calls relevant RPC methods to get the info of fee estimation and tx simulation.
- https://docs.infura.io/api/networks/starknet/json-rpc-methods/starknet_simulatetransactions
- https://docs.infura.io/api/networks/starknet/json-rpc-methods/starknet_estimatefee

Please take into consideration the official docs: 
- https://docs.starknet.io/architecture-and-concepts/network-architecture/fee-mechanism/#when_is_the_fee_charged
- https://www.starknetjs.com/docs/guides/estimate_fees/#fee-limitation

**Comment by penovicp** [comment]
The simulations and estimations you asked about are part of the [Starknet RPC spec](https://github.com/starkware-libs/starknet-specs/tree/v0.7.1/api), so `starknet.js` generates the appropriate results by making requests to the corresponding node endpoints, it doesn't do significant calculations itself. For the mentioned endpoints, the RPC spec prescribes a `block_id` request parameter that is mapped by a corresponding method parameter in `starknet.js`. This parameter can be set as the number of a specific block, or the `latest` and `pending` tags, the `pending` tag is usually used as the default within `starknet.js` and seems to be what you are looking for.

If you need more details I would recommend asking some of the node providers, e.g. [Papyrus](https://github.com/starkware-libs/papyrus), [Pathfinder](https://github.com/eqlabs/pathfinder), [Juno](https://github.com/NethermindEth/juno).
