### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by KhairallahA** [starknet-io/starknet.js#1205]
**Describe the bug**

The site is returning this error:

https://www.starknetjs.com/

![image](https://github.com/user-attachments/assets/57b154a8-065d-4ff2-9a65-54ee09e722fb)

**Comment by theavitw** [comment]
Is that website is this??
![image](https://github.com/user-attachments/assets/d311bad2-5030-43bf-a7f2-ea0ba58db886)

**Comment by KhairallahA** [comment]
@theavitw, ugh yeah why is it not working for me

**Comment by penovicp** [comment]
You can use https://starknet-io.github.io/starknet.js/ while we get the main deployment sorted.

**Comment by KhairallahA** [comment]
@penovicp, cool thank you my man!

**Comment by ivpavici** [comment]
[starknetjs.com/](https://www.starknetjs.com/) is back up!
