### ISSUE TITLE
Failing tests on devnet v0.2.0-rc.x

### ISSUE THREAD

**Issue by ivpavici** [starknet-io/starknet.js#1209]
Due to changes in the blockifier ("A change was made so that re-declaring cairo0 classes also fails with a "already declared" error") integrated into devnet v0.2.0-rc.x  we must go through our tests and apply the logic to circumvent this error 

Job with failing tests:
https://github.com/starknet-io/starknet.js/actions/runs/10507187425/job/29108393106

tests:
-  deploy and test Wallet › simulate transaction - single transaction S0.11.2 › declare tests only on devnet > simulate DECLARE - Cairo 0 Contract
- deploy and test Wallet › Estimate fee bulk & estimate fee › declare tests only on devnet › declare, deploy & multi invoke functions

Error:
` 40: Contract error: {"revert_error":"Class with hash 0x054328a1075b8820eb43caf0caa233923148c983742402dcfc38541dd843d01a is already declared."}`

**Comment by ShantelPeters** [comment]
Please can I be assigned to this issue?
