### ISSUE TITLE
Remove duplicate `ValuesType` import which causes build failure

### ISSUE THREAD

**Issue by lukasaric** [starknet-io/starknet.js#1216]
**Describe the bug**
Build fails because of the duplicate `ValuesType` import in `src/types/lib/index.ts`

**To Reproduce**
run `npm run build`

**Expected behavior**
Build should work

**Screenshots**

**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker]
- Node version [e.g. 16.0.1]
- Starknet.js version
- Network [devnet, testnet]

**Additional context**

**Comment by Jemiiah** [comment]
I would love to work on this…it’s up for contribution yes ??

**Comment by lukasaric** [comment]
> I would love to work on this…it’s up for contribution yes @lukasaric ??

The PR is already created and fixed. I raised an issue just for reference. Sorry!
