### ISSUE TITLE
Documentation from https://github.com/starknet-io/starknet.js/issues/1090, PropertyOrder

### ISSUE THREAD

**Issue by llamitaOnfire** [starknet-io/starknet.js#1225]
Hi, coming from https://github.com/starknet-io/starknet.js/issues/1090, I want to work the propertyOrder section. I already reviewed the @BlackStarkGoku PR as mentioned in the comments and created this issue to work this smaller PR as @ivpavici requested.

**Comment by Iwueseiter** [comment]
Hi @llamitaOnfire can I work on this?

**Comment by martinvibes** [comment]
Hey can i work on this?
