### ISSUE TITLE
Documentation: RequestParser JSDocs

### ISSUE THREAD

**Issue by LuisDi98** [starknet-io/starknet.js#1226]
Hi @ivpavici, I am coming from https://github.com/starknet-io/starknet.js/issues/1090

I want to create the propertyOrder documentation. I created this issue to work this smaller PR. 
Can you help me assign this issue to me? Thanks in advance, looking forward this.

**Comment by ShantelPeters** [comment]
Hi @LuisDi98 please can I be assigned to this issue?

**Comment by LuisDi98** [comment]
> Hi @LuisDi98 please can I be assigned to this issue?

Hi @ShantelPeters, nice to see you want to contribute, but this issue is created to be assigned to me if @ivpavici approves my apply from OnlyDust platform. It means this issue is made for myself just as @ivpavici requested in the original and bigger issue: https://github.com/starknet-io/starknet.js/issues/1090

Go check the description and the comments, so you can do the same and contribute with the sections of documentation that are still missing.

**Comment by ivpavici** [comment]
hi! Unfortunately, we no longer have a budget for external contributions currently... and this particular file has just one function to add the example, so we can cover it internally.

Thanks for reaching out though, if we get more funds I will open issues!
