### ISSUE TITLE
[URGENT] Docs domain expired

### ISSUE THREAD

**Issue by metalboyrick** [starknet-io/starknet.js#1250]
**Describe the bug**
Documentation domain expired. Cannot access documentation site.

**To Reproduce**
Access https://www.starknetjs.com/ on chrome and it will show the screenshot above.

**Expected behavior**
Displays the starknetjs documentation

**Screenshots**
 <img width="1324" alt="image" src="https://github.com/user-attachments/assets/7eea40a6-c203-42ba-9b78-49391c0ca8f7">

**Desktop (please complete the following information):**

(Not relevant)

- Browser & version [e.g. chrome, safari, webworker]
- Node version [e.g. 16.0.1]
- Starknet.js version
- Network [devnet, testnet]

**Additional context**

**Comment by od-hunter** [comment]
Hi @metalboyrick , can I work on this please?

**Comment by ShantelPeters** [comment]
Hello @metalboyrick please can I be assigned to this issue

**Comment by ivpavici** [comment]
domain is back again! thanks!
