### ISSUE TITLE
Enum encoding is different from the SNIP-12 spec

### ISSUE THREAD

**Issue by thiagodeev** [starknet-io/starknet.js#1278]
Hi. I want to talk about this line of code:
https://github.com/starknet-io/starknet.js/blob/01171b0d4962eba56a3adcdd4fc3f4259097acb8/src/utils/typedData.ts#L375

The code only hashes the enum index + the enum parameters but the SNIP-12 says the enum hash is:
`Enc[enum] = hash_array(type_hash(enum), variant_index, Enc[chosen_variant_parameter1],..., Enc[chosen_variant_parameterN])`
(ref: https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md#encoding-4).

AFAIU, it should also hashes the 'type hash' with the index and parameters.

Look at these prints taken when debugging while starknet.js encodes the [enum_example](https://github.com/starknet-io/starknet.js/blob/develop/__mocks__/typedData/example_enum.json):

Here we are encoding [EnumA](https://github.com/starknet-io/starknet.js/blob/develop/__mocks__/typedData/example_enum.json#L10), and the [data](https://github.com/starknet-io/starknet.js/blob/develop/__mocks__/typedData/example_enum.json#L32) is `[2, [0, 1]]`. The code encodes the data to a new array containing the encoded data and passes it with the `variantIndex` variable (value `1`).
![image](https://github.com/user-attachments/assets/7af94c7a-5f9a-453d-ae61-665a48d1ab9d)

Inside the hash function, we can see that only these three values will be hashed, with no mention of the `type hash` value quoted by the spec. The returned value is `'0x583136381661e3eb69d103f2d6f40e6aa190005c3d5c8f0351b080c69602dcb'` to the `EnumA` type.
![image](https://github.com/user-attachments/assets/de62ffe4-a77b-448b-af9f-41ed2b4a6a77)

This is the result of `EnumB` (value: `'0x1fb7169b936dd880cb7ebc50e932a495a60e0084cdab94a681040cb4006e1a0'`):
![image](https://github.com/user-attachments/assets/01a5efec-9563-485d-b912-a33b14fb85e2)

<br><br>
At the end, this will be the result of calling the `getStructHash` function to calculate the hash of the `Example` type.
- `'0x8eb4aeac64b707f3e843284c4258df6df1f0f7fd38dcffdd8a153a495cd351'` is the type hash of `Example`
- `'0x583136381661e3eb69d103f2d6f40e6aa190005c3d5c8f0351b080c69602dcb'` is the hash of `EnumA`
- `'0x1fb7169b936dd880cb7ebc50e932a495a60e0084cdab94a681040cb4006e1a0'` is the hash of `EnumB`.

This is correct for the `Example` type, since the [spec](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md#encoding) says that this is the default for object types (`Enc[x] = hash_array(type_hash(MyObject), Enc[param1], Enc[param2], ..., Enc[paramN])`), but the values of the `EnumA` and `EnumB` encoding are theoretically wrong since they were calculated without the `type hash` value. So, it's a wrong result after all.
![image](https://github.com/user-attachments/assets/594f1665-6e74-4955-acc2-c333c9c45867)

What do you think guys? Please let me know if I misunderstood something.

**Comment by penovicp** [comment]
@thiagodeev Good catch, thank you for reporting it!

I opened PR #1281 that should address the issue, I would appreciate it if you could take a look.

**Comment by thiagodeev** [comment]
Thanks!
LGTM. I compared your test result with the one made on starknet.go and they are the same
