### ISSUE TITLE
Error when derive a stark key

### ISSUE THREAD

**Issue by MeoMunDep** [starknet-io/starknet.js#1282]
When i derive a EVM private key to a Stark Net publickey it occur this errors: `Expected valid bigint: 0 < bigint < curve.n`

Here is the code if you want to check:

 const { ec, encode } = require('starknet');

const privateKey =
  '0x....';

try {
  const starknetPublicKey = ec.starkCurve.getStarkKey(privateKey);
  const fullPublicKey = encode.addHexPrefix(
    encode.buf2hex(ec.starkCurve.getPublicKey(privateKey))
  );

  console.log('Starknet Public Key:', starknetPublicKey);
  console.log('Full Public Key:', fullPublicKey);
} catch (error) {
  console.error(error.message);
}

**Desktop (please complete the following information):** Window11

- Browser & version [e.g. chrome, safari, webworker]
- Node version [22.11.0]
- Starknet.js version: Lastest - 6.11.0

**Comment by penovicp** [comment]
This isn't a bug. The underlying key cryptography of Ethereum and Starknet is different and isn't interchangeable.

If you are trying to use an Ethereum signature based account you should use the [EthSigner class](https://starknetjs.com/docs/guides/create_account#create-an-ethereum-account).
