### ISSUE TITLE
use case for account.verifyMessage() and .verifyMessageHash() 

### ISSUE THREAD

**Issue by PhilippeR26** [starknet-io/starknet.js#529]
**Describe the bug**
I have some doubt about the use-case of 2 functions : account.verifyMessageHash() and account.verifyMessage().
I have been alerted by a user on Discord, who was lost on this subject.
For me, only people without the privKey have interest to use these functions.
But as they are not static methods, you need to create an account object to access to these functions. Create an account object needs the privKey.
It means that you need to have the privKey to access to functions useful for non privKey holders….

**Expected behavior**
ec.verify() function has sense, because it do not need a privKey.
My feeling is that these 2 functions should be shadowed in doc, because I see no practical use-case for DAPP devs.

**Desktop (please complete the following information):**

- Browser & version : N/A
- Node version N/A
- Starknet.js version v4.17.1
- Network N/A

**Comment by tabaktoni** [comment]
> But as they are not static methods, you need to create an account object to access to these functions. Creating an account object needs the privKey.
> It means that you need to have the privKey to access functions useful for non-privKey holders….

You can create an Account object with a custom implementation of the Signer, as so using secondary privKey.
But you also have a point there regarding usage, I do not know what use cases are there.
@janek26 @dhruvkelawala Are you guys using these is wallets or what is the use-case here ?

**Comment by PhilippeR26** [comment]
OK. Will have a look.
