### ISSUE TITLE
Deprecate the sequencer Api and make RPC the default

### ISSUE THREAD

**Issue by ivpavici** [starknet-io/starknet.js#642]
**Is your feature request related to a problem? Please describe.**
Going forward, the sequencer API will no longer work. So the time has come to start encouraging users to the RPC provider.

**Describe the solution you'd like**
- We should put the RPC provider as the default one.
- Also we should mark the sequencer API-s as deprecated

**Comment by tabaktoni** [comment]
I will recommend making RPC the Default provider as soon as RPC 0.4.0 become stable
