### ISSUE TITLE
casing: `Starknet` instead of `StarkNet`

### ISSUE THREAD

**Issue by pscott** [starknet-io/starknet.js#705]
**Is your feature request related to a problem? Please describe.**
The official casing for `Starknet` is not `StarkNet` anymore, but `Starknet`.
However, some occurrences of `StarkNet` can still be found, most notably in the TypeHash function:
https://github.com/0xs34n/starknet.js/blob/384db9f3bfaf066dea43f60e49f255c9a4a28b63/src/utils/typedData.ts#L255-L256

**Describe the solution you'd like**
Replace every occurence of `StarkNet` with `Starknet`

**Describe alternatives you've considered**
Keep `StarkNet` and dismiss this issue. I think it's still early enough to change to `Starknet` though.

**Additional notes**
This introduces a big breaking change (:

**Comment by 0xdorifto** [comment]
Hey! Can this issue be assigned to me?

**Comment by tabaktoni** [comment]
@0xdorifto Yes feel free to take it

**Comment by 0xdorifto** [comment]
@tabaktoni thanks! I'll start working on it now.

**Comment by pscott** [comment]
> @0xdorifto Yes feel free to take it

should we discuss if it's worth introducing the breaking change?

**Comment by PhilippeR26** [comment]
Not sure it's still early enough to change.

**Comment by 0xdorifto** [comment]
It's up here if you guys want to check it out ^

**Comment by ivpavici** [comment]
Will probably be able to close this after this one is closed https://github.com/starknet-io/get-starknet/pull/194

**Comment by PhilippeR26** [comment]
Will at the end be defined by this snip : https://community.starknet.io/t/snip-off-chain-signatures-a-la-eip712/98029#abstract-1

**Comment by tabaktoni** [comment]
Resolved in favor of the snip, for further progress push change's on the snip
