### ISSUE TITLE
Update OZ contracts to v0.7.0-rc.0 in tests

### ISSUE THREAD

**Issue by ivpavici** [starknet-io/starknet.js#731]
In our tests we should bump at some point to the newest OZ contracts:
https://github.com/OpenZeppelin/cairo-contracts/releases/tag/v0.7.0-rc.0

**Comment by PhilippeR26** [comment]
I already compiled account and erc20/721 (Sierra & Casm are available in my tuto repo).
They needs Cairo v2.2.0 to compile.
So we need to wait until networks use cairo v2.2.0 (currently v2.1.0).

**Comment by PhilippeR26** [comment]
For info, I made some tests of multicall.
If the Account instance is well configured as type "1", it works fine.
