### ISSUE TITLE
Investigate Netlify preview inaccuracies

### ISSUE THREAD

**Issue by penovicp** [starknet-io/starknet.js#750]
The Netlify preview build seems to be inaccurate. 

For PR #747 the JSDOC description changes for e.g. [`isCairo1Abi`](https://deploy-preview-747--starknetjs.netlify.app/docs/next/API/namespaces/cairo#iscairo1abi) should read `Test if an ABI comes from a Cairo 1 contract`, however, the older `tells if an ABI comes from a Cairo 1 contract` is displayed.

**Comment by tabaktoni** [comment]
What is status on this ?

**Comment by penovicp** [comment]
I think it might have been resolved by #781. Haven't come up with a test to fully confirm it.
