### ISSUE TITLE
Starknet.js to handle several versions of rpc specification

### ISSUE THREAD

**Issue by PhilippeR26** [starknet-io/starknet.js#760]
**Is your feature request related to a problem? Please describe.**
Improvement :
PathFinder is able to handle rpc specifications 0.3.0 and 0.4.0, and it's useful.
Starknet.js could have something similar. By this way, the DAPP dev can use the last up to date  version of Starknet.js (with cool new features, and some bugs removed), and can at the same time be able to connect to his favorite node that has not yet been updated to the last version of rpc spec.
The rpc spec 0.4.0 is released for months now, but the migration from rpc 0.3.0 to 0.4.0 is not yet performed in all nodes. Could be the same mess for the next revisions of this rpc spec.

**Describe the solution you'd like**
To be able to create a RpcProvider with an optional rpc version parameter : 
```typescript
const providerAlchemyMainnet = new RpcProvider({ 
    nodeUrl: 'https://starknet-mainnet.g.alchemy.com/v2/' + alchemyKey, 
    rpcVersion: "0.3.0"
});
const providerInfuraMainnet = new RpcProvider({ 
    nodeUrl: 'https://starknet-mainnet.infura.io/v3/' + infuraKey,
    rpcVersion: "0.4.0"
 });
```

**Describe alternatives you've considered**
No new code, no new bug.

**Comment by tabaktoni** [comment]
Cons
- with supporting multiple RPC versions, the codebase will become impossible to maintain with current resources.
- Not implementing it we force Daps to move forward with the codebase
- proper method will be Project versioning and support multiple versions which is impossible in the current setup

Pros
- Daps can move forward slower

Nodes need to do this to smooth the transition, as it is much harder to run an older node and still be compatible with the rest of the network, opposite to the client side where certain features will work even with outdated versions.
Alago is a Backend with API versioning, but Frontend is only one.

So I am firmly against supporting multiple RPCs in the same codebase.
My proposal is to rethink this once the network matures, and then maybe support multiple versions with different RPC

**Comment by tabaktoni** [comment]
So I did support 0.5 and 0.6 in the same codebase, it is not flagged not provider pure separation as it is mostly diff in add V3.
We will see how to handle this in the future when there is not just a diff add but del/remove/refactor.
Closing for now as resolved
