### ISSUE TITLE
Execution was reverted

### ISSUE THREAD

**Issue by aibobaby** [starknet-io/starknet.js#767]
**Describe the bug**

Every transaction will fail and the following prompt will appear. I have repeatedly reinstalled the plug-in and switched to different browsers, including chrome and firefox, but it does not work.

pl: Execution was reverted; failure reason: [0x617267656e742f696e76616c69642d677561726469616e2d736967].

**Screenshots**
![WechatIMG980](https://github.com/starknet-io/starknet.js/assets/115474636/02dc257f-4702-4d6f-8d50-94c5db56f348)

**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker]
- chrome and firefox
- argent x version:v5.8.4

**Additional context**
Since upgrading argent x version:v5.8.4, it can no longer be used. When connecting to a dapp transaction, the dapp sometimes prompts user abort
![WX20230922-223110@2x](https://github.com/starknet-io/starknet.js/assets/115474636/07c9dd16-7a02-4284-b5a2-55e026b3f5d7)

**Comment by mbzdg** [comment]
Hex Message : ?argent/invalid-guardian-sig

What does it mean. Why the argentx wallet upgrade messed up.

**Comment by penovicp** [comment]
This should be reported to Argent. It does not appear to be a starknet.js issue.
