### ISSUE TITLE
Is there a way to compute the transaction_hash before invocation?

### ISSUE THREAD

**Issue by arijoon** [starknet-io/starknet.js#770]
Basically pre-compute the hash before sending a request to the provider or sequencer, in order to safely recover in case of network failures and determine whether the transaction was broadcast or not

**Comment by arijoon** [comment]
found this here https://github.com/starknet-io/starknet.js/blob/2198e7d56b90825cc3022fd128f9d159be01aeda/src/utils/hash.ts#L143-L161

I was checking some old PRs and it seems to have been moved hence harder to find. Would be very beneficial to add these to the documentation as I highly recommend pre-computing the hash and tracking it before broadcasting transactions

**Comment by tabaktoni** [comment]
It is part of the API Docs:
https://www.starknetjs.com/docs/API/namespaces/hash#calculatetransactionhash

**Comment by arijoon** [comment]
> It is part of the API Docs: https://www.starknetjs.com/docs/API/namespaces/hash#calculatetransactionhash

Thanks, is there an easier way to search the API docs without knowing the specific namespace to look under? I cloned the repo and started searching within the codebase and that was far easier. if its possible to add search capabilities across all namespaces it would make it much simpler to use the online docs. I wouldn't say its urgent however, still relatively easy to search even in github and find things as they are named very well (with the exception of _cairo1 functions which threw me off for a while as I didn't know defaults were cairo0 for most functions on the version I was using)
