### ISSUE TITLE
bug: default value doesn't exists as mentioned in docs

### ISSUE THREAD

**Issue by lambda-0x** [starknet-io/starknet.js#773]
**Describe the bug**

I know this function is deprecated but i needed to use it for a CTF.

[description of `Invocation`](https://www.starknetjs.com/docs/api/namespaces/types/#invocation) type says that the default value for `signature` is `[]`. 

but when its not specificed an error is thrown

```
    throw Error("formatSignature: provided signature is undefined");
```
**To Reproduce**
call `invokeFunction` without specifying `signature` field

**Expected behavior**
`signature` should use empty array as default value

**Additional context**
I am willing to open a PR for this if needed.

**Comment by tabaktoni** [comment]
> [description of `Invocation`](https://www.starknetjs.com/docs/api/namespaces/types/#invocation) type says that the default value for `signature` is `[]`.
I am not sure it says anything about the default value. It says it is undefined or ..., on that point, invokeFunction because of formatSignature does need sig even doe it is optional, this could be the issue referring to?

**Comment by lambda-0x** [comment]
sorry i meant to link this in the issue : https://www.starknetjs.com/docs/API/classes/Provider#invokefunction

![image](https://github.com/starknet-io/starknet.js/assets/87354252/ad76b85c-6b2b-44e0-ad59-54f071047a04)


> Error is there to prevent unintentional undefined signature, but it should allow you to provide an empty array as a signature if you intentionally want to do it.

yeah that make sense, i think then we just need to update doc saying that its required field.

**Comment by lambda-0x** [comment]
> Once corrected, this type is used only in Account.execute() and Contract.invoke() ; both functions will pass a mandatory Starknet standard signature to invokeFunction().
> 
> So, it seems that signature could be mandatory in Invoke (with probably impacts in cascade in the code).

@PhilippeR26  starknet doesn't mandate signature, its upto the account contract implementer to decide how to use passed in signature (signature can be avoided altogether).

without `invokeFunction` it wouldn't be possible to call an account contract whose keys you don't have. even thought they don't require it. is there any alternate way to do this (what i want basically is `Account` without private key)?

**Comment by PhilippeR26** [comment]
> > Once corrected, this type is used only in Account.execute() and Contract.invoke() ; both functions will pass a mandatory Starknet standard signature to invokeFunction().
> > So, it seems that signature could be mandatory in Invoke (with probably impacts in cascade in the code).
> 
> @PhilippeR26 starknet doesn't mandate signature, its upto the account contract implementer to decide how to use passed in signature, signature can be avoided altogether (althought that would be very rare)
> 
> without `invokeFunction` it wouldn't be possible to call an account contract whose keys you don't have. even thought they don't require it. is there any alternate way to do this (what i want basically is `Account` without private key)?

That's why i used the word **standard** about signature handled by Starknet.js. Today Starknet.js latest version v5.21.0 isn't coded to handle account abstraction about hash and signature.
It will come soon with merge of PR #748 .

**Comment by PhilippeR26** [comment]
And I have some difficulties to see the interest to pay to use a blockchain,  using an account that do not  provides any safety of a crypto signature.

**Comment by lambda-0x** [comment]
> And I have some difficulties to see the interest to pay to use a blockchain, using an account that do not provides any safety of a crypto signature.

there probably isn't a good reason for it directly. I just happened to need to use it in a CTF.

**Comment by muheebyusufbaba1** [comment]
I will like to fix this for ODHack @ivpavici

**Comment by PhilippeR26** [comment]
In fact, this one should probably not be tagged as ODHack, and should have been closed.
To authorize a transaction without signature is a clear safety issue and should never occur.
I urge you to choose a different issue.
