### ISSUE TITLE
Problems in type CompiledSierraCasm

### ISSUE THREAD

**Issue by PhilippeR26** [starknet-io/starknet.js#797]
**Describe the bug**
If you read a CASM file with 
```typescript
const contractCasm: CompiledSierraCasm = json.parse(fs.readFileSync("./compiledContracts/cairo210/hello.casm.json").toString("ascii"));
```
you will have no error.

But if you do not want to use the `fs` library (for a website for example), you will use such code :
- a .ts file describing the CASM :
``` typescript
import { CompiledSierraCasm } from "starknet";
export const importedContractCasm: CompiledSierraCasm = {
  "prime": "0x800000000000011000000000000000000000000000000000000000000000001",
  "compiler_version": "2.1.0",
  "bytecode": [
    "0xa0680017fff8000",
    "0x7",
    ...
```
-   a script :
```typescript
import { importedContractCasm } from "./hello.casm.json"; // Cairo v2.1.0
const importedCasmCH = hash.computeCompiledClassHash(importedContractCasm);
```
This code will generate errors due to non conformity to type `CompiledSierraCasm` :
- Pythonic_hints is optional in the CASM file, but is mandatory in Starknet.js :
```typescript
export type CairoAssembly = {
  prime: string;
  compiler_version: string;
  bytecode: ByteCode;
  hints: any[];
  pythonic_hints: PythonicHints;
  entry_points_by_type: EntryPointsByType;
};
```
- The Casm file has entrypoints.offset as number type, by Starknet.js is expecting a string :
```typescript
export type ContractEntryPointFields = {
  selector: string;
  offset: string ;
  builtins?: Builtins;
};
```

**To Reproduce**
https://github.com/PhilippeR26/starknet.js-workshop-typescript/blob/main/src/scripts/utils/1.testCairoCasm.ts

**Expected behavior**
Raw Casm file can be imported.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker] : N/A
- Node version [e.g. 16.0.1] : N/A
- Starknet.js version : 5.21.1
- Network [devnet, testnet] : N/A

**Additional context**
There is a workaround, but it's not clean :
convert the formated json as a string file :
```typescript
const contractCasm: CompiledSierraCasm = json.parse(fs.readFileSync("./compiledContracts/cairo210/hello.casm.json").toString("ascii"));
fs.writeFileSync("./test.json.ts", json.stringify(contractCasm));
```
Then in the file :
```typescript
export const importedContractCasmString = '{"prime":"0x800000000000011000000000000000000000000000000000000000000000001","compi ....
```
and in the script :
```typescript
import { importedContractCasmString } from "./test.json";
const afterImport:CompiledSierraCasm=json.parse(importedContractCasmString);
const importedCasmStringCH = hash.computeCompiledClassHash(afterImport);
```
It works, but it's dirty code...

**Comment by PhilippeR26** [comment]
I tested a solution in a new branch of Starknet.js :
with :
```typescript
pythonic_hints?: PythonicHints;
```
and 
```typescript
offset: string | number;
```

It works, but to build, it's necessary to modify also this :
https://github.com/PhilippeR26/starknet.js/blob/3c3d6b6df0b43648fdd8d8d3d979a0573c707084/src/types/api/openrpc.ts#L302-L304

**Comment by tabaktoni** [comment]
Yea, i have opened PR https://github.com/starkware-libs/starknet-specs/pull/152
To bring atention to this issue, it should be number or string to cover all cases.

You can create PR based on this, I refactored openrpc file into multiple so conflicts will be resolved on merge, and this modification will jump into rpc.ts, which is file for overriding official spec.

**Comment by tabaktoni** [comment]
If you want fewer conflicts you can base PR on this one https://github.com/starknet-io/starknet.js/pull/798.
You can also test new Test setup :D

**Comment by PhilippeR26** [comment]
in PR #799

**Comment by tabaktoni** [comment]
Resolved
