### ISSUE TITLE
[V6] Implement DataType Snip

### ISSUE THREAD

**Issue by tabaktoni** [starknet-io/starknet.js#816]
https://community.starknet.io/t/snip-off-chain-signatures-a-la-eip712/98029

TODO: Elaborate steps

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by makhdoom13** [comment]
apply passport gitcoin sybil score

**Comment by PhilippeR26** [comment]
Is something frozen about this SNIP?
