### ISSUE TITLE
[V6] Lower timer - speed up

### ISSUE THREAD

**Issue by tabaktoni** [starknet-io/starknet.js#827]
**Is your feature request related to a problem? Please describe.**
After refactoring waitForTransaction on [v5.23.0](https://github.com/starknet-io/starknet.js/releases/tag/v5.23.0), it is possible now to lower timeout to 1s and gain ~x2.5 performance.
However, some contract tests still failed at this speed.
This feature needs more testing / communicating with nodes regarding the "Readiness" status for TX.
At the moment even though the transaction status is SUCCEEDED and ACCEPTED_ON_L2 pending block nodes are not ready to work with the contract/transaction.
Investigate for contract do we need to check that the latest block, instead of pending?
For transactions why txHash is unknown if the status is SUCCEEDED and ACCEPTED_ON_L2 on pending Block

**Describe the solution you'd like**
Lower RPC retryInterval to 1000 ms.

**Describe alternatives you've considered**

**Additional context**

**Comment by vibenedict** [comment]
Hi, i will like to take up this issue.
