### ISSUE TITLE
provider.waitForTransaction() is not handling correcly its optional parameters

### ISSUE THREAD

**Issue by PhilippeR26** [starknet-io/starknet.js#859]
**Describe the bug**
In provider.waitForTransaction(), `errorStates` optional parameter is not taken into account.

Reported in [Discord](https://discord.com/channels/793094838509764618/927918707613786162/1179706691487539280)

**To Reproduce**
```typescript
const tx = await this.adminAccount.execute(calls);
let tx_receipt = await this.l2Provider.waitForTransaction(
     tx.transaction_hash,
      {
         successStates: [TransactionFinalityStatus.ACCEPTED_ON_L2],
         errorStates: [TransactionExecutionStatus.REVERTED],
      },
);
console.log(tx_receipt);
```
do not throw error in case of transaction reverted.

**Expected behavior**
this method should throw Error in accordance with `errorStates` optional parameter.

**Screenshots**
N/A
**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker]
- Node version [e.g. 16.0.1]
- Starknet.js version v5.24.3
- Network [devnet, testnet] any

**Additional context**
N/A

**Comment by PhilippeR26** [comment]
I analyzed this problem.
In fact, it's very easy to solve : just test first `errorStates` cases, then `executionStatus` cases. 
Because in this case :
```typescript
{ 
executionStatus : "ACCEPTED_ON_L2",
errorStates : "REVERTED"
}
```
if you test first `executionStatus`, you don't see the error!

Code modified :
```typescript
if (errorStates.includes(executionStatus) || errorStates.includes(finalityStatus)) {
    const message = `${executionStatus}: ${finalityStatus}`;
    const error = new Error(message) as Error & { response: RPC.TransactionStatus };
    error.response = txStatus;
    isErrorState = true;
    throw error;
  } else if (
    successStates.includes(executionStatus) ||
    successStates.includes(finalityStatus)
  ) {
    onchain = true;
  }
  ```
  
  Nevertheless, by default, this method throw an error if the transaction is not succeeded.
  As PR #851 will ease the interpretation of the receipt, I propose to have by default no Error for REVERTED and REJECTED status.
  Your position?

**Comment by tabaktoni** [comment]
We need to also add a test with all permutations of response statuses on waitForTransaction

**Comment by penovicp** [comment]
I opened #874 so it can serve as a bug-fix for v5. We can appraise changes to the current behavior for v6 as part of #796.
