### ISSUE TITLE
calculateContractAddressFromHash

### ISSUE THREAD

**Issue by ittaysw** [starknet-io/starknet.js#876]
**Describe the bug**
I think the implementation is wrong. The cairo implementation calculates the hash but the modulus it by `const ADDR_BOUND = 2 ** 251 - MAX_STORAGE_ITEM_SIZE;` where `const MAX_STORAGE_ITEM_SIZE = 256;`

**Comment by ittaysw** [comment]
Similarly, `validateAndParseAddress` is not correct as the upper bound should be 2**251-256

**Comment by penovicp** [comment]
@ittaysw You are right. Thank you for reporting these!
