### ISSUE TITLE
account.execute is error: LibraryError: 40: Contract error; at node.

### ISSUE THREAD

**Issue by Alan-Cn** [starknet-io/starknet.js#887]
const account = new Account(
          provider,
          STARKNET_ADDRESS,
          STARKNET_PRIVATE_KEY
        );
      
      const crossContract = new Contract(
        STARKNET_OB_SOURCE_ABI,
        contractAddress,
        account
      );
      const transferERC20TxCall = crossContract.populate("transferERC20", [
        tokenAddress,
        receiverAddress,
        getUint256CalldataFromBN(String(amount)),
        l1Address,
      ]);
      tx = await account.execute(transferERC20TxCall);

**Comment by PhilippeR26** [comment]
I think that it's not a bug. You will find a personalized support in our Discord : https://discord.com/channels/793094838509764618/927918707613786162

**Comment by Alan-Cn** [comment]
can u give me a invite url?




Alan
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "starknet-io/starknet.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月11日(星期一) 下午4:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [starknet-io/starknet.js] account.execute is error: LibraryError: 40: Contract error; at node. (Issue #887)





 
I think that it's not a bug. You will find a personalized support in our Discord : https://discord.com/channels/793094838509764618/927918707613786162

**Comment by penovicp** [comment]
Invite link: https://discord.gg/qypnmzkhbc
