### ISSUE TITLE
Add `eth_signer` in addition to the default signer

### ISSUE THREAD

**Issue by ivpavici** [starknet-io/starknet.js#888]
We will soon have Eth signature based accounts in Starknet (WIP by OpenZeppelin). They’re basically the same as the standard accounts with starkcurve based ECDSA replaced by secpk256k1 based ECDSA.

The request is about  adding `eth_signer` in addition to the default signer, allowing devs who rely on eth accounts to test directly with starknet-js. noble-curves has the curve definition [here](https://github.com/paulmillr/noble-curves/blob/2f1460a4d7f31e5a61db9606266f5b9a5c659c9d/src/secp256k1.ts#L47), so IIUC the signer code is very similar (as .sign comes from the curve object

**Comment by PhilippeR26** [comment]
Under progress...
