### ISSUE TITLE
Support blockTag in function calls

### ISSUE THREAD

**Issue by swan-of-bodom** [starknet-io/starknet.js#896]
Feature:

Support the use of blockTag in function calls to allow to get for example the `totalSupply` of a token at a specific block number.

**Comment by tabaktoni** [comment]
This should already be possible, we need to test it and see if it is broken.
@swan-of-bodom How did you used function
`contract.fname() or contract.call(...) `
The best will be to provide an example you expect to work.

**Comment by swan-of-bodom** [comment]
Hi @tabaktoni realised it's already working by using `blockIdentifier` instead of blockTag.
