### ISSUE TITLE
Simplify decoding javascript objects from field elements.

### ISSUE THREAD

**Issue by fracek** [starknet-io/starknet.js#929]
**Is your feature request related to a problem? Please describe.**

I often want to decode a list of field elements into a javascript object. The issue is that the parsing functions are hidden inside starknet.js and not available to us.

**Describe the solution you'd like**

I'd like a `decodeAbiParameters` function that decodes a list of field elements into javascript objects. With some examples:

```ts
const abi = [
  {
    type: 'struct',
    name: 'example::TestStruct',
    members: [
      {
        name: 'low',
        type: 'core::integer::u128',
      },
      {
        name: 'low',
        type: 'core::integer::u128',
      },
    ],
  },
] as const;

decodeAbiParameters(abi, ['example::TestStruct', 'example::TestStruct'], [0n, 1n, 2n, 3n])
// => [{ low: 0, high: 1 }, { low: 2, high: 3 }]
```

The first parameter is the abi, to lookup any complex type. The second parameter contains the root types of what I'm going to decode, in this case two test struct. The third parameter is the raw list of field elements. The return value is a list of the same length as the second argument but with the elements decoded.

I believe it can be made type safe with abi-wan.

**Additional context**

I believe this is basically the code used to decode the return value of functions and of events. So it's a matter of encapsulating that code and making available to users.

**Comment by PhilippeR26** [comment]
For abi-wan, I don't know. To implement seems easy ; 90% of the code is already existing.
Do you have a preference for the version(s) to implement? V5, V6, V5& V6?

**Comment by fracek** [comment]
Obviously if possible it would be great to have it in v5 & v6 :)

**Comment by PhilippeR26** [comment]
If the array of numbers is the response of a View function of the contract, you can already decode this way : 
```typescript
const helloCallData = new CallData(compiledSierra.abi);
    const res = helloCallData.parse("get_user1",["0x123456","0x1"]);
    ```
    result : 
    ```json
    { address: 1193046n, is_claimed: true }
    ```
    Anyway, I an digging to have the answer for just one number/struct/Enum.

**Comment by PhilippeR26** [comment]
It's super easy to have something like this :
```typescript
const helloCallData=new CallData(compiledSierra.abi);
const inputType:AbiEntry={name:"hello::hello::UserData",type:"struct"}
const res2=helloCallData.decodeParameters(inputType,["0x123456"]);
```
It will be a bit more complicated without `type`.

**Comment by fracek** [comment]
Looks like the second one does exactly what I mean.

**Comment by PhilippeR26** [comment]
Yes, but `.decodeParameters`  has to be created.
@ivpavici could you affect me to this issue?

**Comment by PhilippeR26** [comment]
I have started to perform tests.
I ended for Cairo 0. It works (struct, tuple,...), except for array, that can't be handled with only one input.
I will work this afternoon on Cairo 1 tests.

**Comment by PhilippeR26** [comment]
And the Cairo 1 tests are a full success :
All these lines are working fine : 
```typescript
const res2 = helloCallData.decodeParameters("hello::hello::UserData", ["0x123456", "0x1"]);
const res3 = helloCallData.decodeParameters(["hello::hello::UserData", "hello::hello::UserData"], ["0x123456", "0x1", "0x98765", "0x0"]);
const res4 = helloCallData.decodeParameters("core::integer::u8", ["0x123456"]);
const res5 = helloCallData.decodeParameters("core::bool", ["0x1"]);
const res6 = helloCallData.decodeParameters("core::felt252", ["0x123456"]);
const res7 = helloCallData.decodeParameters("core::integer::u256", ["0x123456", "0x789"]);
const res8 = helloCallData.decodeParameters("core::array::Array::<core::integer::u16>", ["2", "0x123456", "0x789"]);
const res9 = helloCallData.decodeParameters("core::array::Span::<core::integer::u16>", ["2", "0x123456", "0x789"]);
const res10 = helloCallData.decodeParameters("(core::felt252, core::integer::u16)", ["0x123456", "0x789"]);
const res11 = helloCallData.decodeParameters("core::starknet::eth_address::EthAddress", ["0x123456"]);
const res12 = helloCallData.decodeParameters("core::starknet::contract_address::ContractAddress", ["0x123456"]);
const res13 = helloCallData.decodeParameters("core::starknet::class_hash::ClassHash", ["0x123456"]);
const res14 = helloCallData.decodeParameters("core::option::Option::<core::integer::u8>", ["0", "0x12"]);
const res15 = helloCallData2.decodeParameters("core::result::Result::<hello_res_events_newTypes::hello_res_events_newTypes::Order, core::integer::u16>", ["0", "0x12","0x345"]);
const res16 = helloCallData.decodeParameters("hello::hello::MyEnum", ["0", "0x12", "0x5678"]);
```
with this result :
```
res2 = { address: 1193046n, is_claimed: true }
res3 = [
  { address: 1193046n, is_claimed: true },
  { address: 624485n, is_claimed: false }
]
res4 = 1193046n
res5 = true
res6 = 1193046n
res7 = 0x78900000000000000000000000000123456
res8 = [ 1193046n, 1929n ]
res9 = [ 1193046n, 1929n ]
res10 = { '0': 1193046n, '1': 1929n }
res11 = 1193046n
res12 = 1193046n
res13 = 1193046n
res14 = CairoOption { Some: 18n, None: undefined }
res15 = CairoResult { Ok: { p1: 18n, p2: 837n }, Err: undefined }
res16 = CairoCustomEnum {
  variant: {
    Response: { p1: 18n, p2: 22136n },
    Warning: undefined,
    Error: undefined
  }
}
```
I will clean up all this, and propose a PR.
