### ISSUE TITLE
Event Decoding not functional for addresses 

### ISSUE THREAD

**Issue by NBMSacha** [starknet-io/starknet.js#930]
**Describe the bug**
The event parser is returning a bigint for addresses, and isn't handling the "contract address" core type (which ends up being converted to a bigint as well)

**To Reproduce**
Simply try to parse any event containing an address.

**Expected behavior**
Event should be parsed as an address, with string type.

- Node version: all
- Starknet.js version: latest
- Network: all 

**Additional context**
Already fixed it, would love to contribute by opening a PR

**Comment by PhilippeR26** [comment]
Hello,
Could you provide a contract address with such specificity, and a transaction hash of this contract with the problem?

**Comment by ivpavici** [comment]
@NBMSacha can you give more details or share the PR?

**Comment by ivpavici** [comment]
closing as stale
