### ISSUE TITLE
Performance degradation on v6

### ISSUE THREAD

**Issue by ivpavici** [starknet-io/starknet.js#937]
We observe a slowdown when running tests on the `beta` branch, which will eventually become Starknet.js v6.

Examples: 
- on latest v5 (currently develop branch):  __tests__/account.test.ts (**90.367 s**)  (working with RPC v0.5.1)
- on latest v6 (currently beta branch): __tests__/account.test.ts (**261.338 s**) (working with RPC v0.6)

Tests are running on devnet-rs: https://github.com/0xSpaceShard/starknet-devnet-rs

beta CI example: https://github.com/starknet-io/starknet.js/actions/runs/7627795895/job/20777335303

**Comment by NandyBa** [comment]
Happy to explorer and work on that

**Comment by CollinsC1O** [comment]
Hi @ivpavici I would love to work on this

**Comment by CollinsC1O** [comment]
Ok thanks @ivpavici

**Comment by ivpavici** [comment]
related https://github.com/0xSpaceShard/starknet-devnet-rs/issues/293

**Comment by lukasaric** [comment]
Hey!
Yes, I’m looking into this one. Sry for not writing down here. :/ 
@ivpavici
