### ISSUE TITLE
Donating Funds to Starknet.js

### ISSUE THREAD

**Issue by Lfada** [starknet-io/starknet.js#944]
Hi Starknet.js maintainers. I'm Lucas, a core contributor to the Drips project (https://www.drips.network/). I help recipients of donations through their learning and onboarding process.

Snapshot has been using https://github.com/starknet-io/starknet.js. It's one of their most critical dependencies!

Snapshot’s core contributors appreciate the work you all do and want to make sure that you are all well-funded to keep doing it. For that reason, they have decided to donate some funds to your project through [Drips](https://www.drips.network/)

Who can I talk to about it?

cc: @tabaktoni @janek26 @dhruvkelawala @penovicp

**Comment by tabaktoni** [comment]
Thank you [Lfada](https://github.com/Lfada), we will check what wallet to use as primary to set it up.

**Comment by tabaktoni** [comment]
All set and done

**Comment by Lfada** [comment]
Amazing, thank you @tabaktoni ! 

Great to see you split to Paul Miller from Noble-Curves and [abi-wan-kanabi](https://github.com/keep-starknet-strange/abi-wan-kanabi), which I think it's great to support FOSS specifically focused on the Starknet ecosystem :) 

Any chance you would have time to hop on a call with us to share feedback and give us your opinion on some directions we are taking?

**Comment by ivpavici** [comment]
_Any chance you would have time to hop on a call with us to share feedback and give us your opinion on some directions we are taking?_
- sure! reach out to tt and ipa @spaceshard.io

**Comment by Lfada** [comment]
Amazing, just sent an email to @spaceshard.io to coordinate. Couldn't message you directly on tw unfortunately.

**Comment by ivpavici** [comment]
@Lfada I didn't get any mail :/ on TW I think I disabled messages from people I don't follow so you can drop me your TW!

**Comment by Lfada** [comment]
@ivpavici sure thing: https://twitter.com/lukfada

drop me a message and we coordinate. Any of you going to EthDenver?
