### ISSUE TITLE
Add support for SNIP-9

### ISSUE THREAD

**Issue by ivpavici** [starknet-io/starknet.js#948]
More details:

https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-9.md

Initial thoughts (credits to @PhilippeR26 ):
- We need a function that will create TypedData, hash it, and include all this in an object that will be the result of the function. (Nothing is explained in the snip how to construct this TypedData, and which hash to use)
- support the call of the entrypoint `execute_from_outside` 
- We need also a function that checks that an account contract can handle this type of tx, and then send this special tx ( `execute_from_outside` ).

**Comment by kfastov** [comment]
Hello! Can I please tackle this one?
I've implemented SNIP-12 signatures verification on-chain (which seems related) and participated in the previous ODHack.
I plan to study the related SNIPs, and discuss with community all details that are unclear,
check the documentation of the `execute_from_outside` entrypoint and its source code if needed, and then implement the functions mentioned in this task

**Comment by ivpavici** [comment]
ok, sure @kfastov good luck!
