### ISSUE TITLE
Resolve package dependency on Abi Wan

### ISSUE THREAD

**Issue by tabaktoni** [starknet-io/starknet.js#957]
**Describe the bug**
starknet@5.24.3 - 7.7MB / 14 packages
starknet@6.0.0 - 123MB / 46 packages

The issue is in Abi wan CLI packages for js to ts conversion
This is both security and package size issue.
We want to reduce dependency graph to lowest possible footprint

**To Screenshots**
![1](https://github.com/starknet-io/starknet.js/assets/923054/506b2118-0305-41f1-b866-9ee8f26e02d6)
![2](https://github.com/starknet-io/starknet.js/assets/923054/e2583a15-ec4a-4332-a1ad-412d531d819a)

**To Reproduce**
https://pkg-size.dev/starknet@5.24.3
https://pkg-size.dev/starknet@6.0.0

**Additional context**
My recommendation for fixing this is:
- removing any non-essential stuff from abi-wan dependency
- remove script for js -> ts conversion from abi-wan package and deploy separately to npm
- script is used with npx so it doesn't need to be part of default package
- fix abi one dist to only TS decoder/encoder with no additional files besides dist
- use same TS versions so npm do not install both [v4.9.5](https://www.npmjs.com/package/typescript/v/4.9.5) and [typescript v5.3.3](https://www.npmjs.com/package/typescript/v/5.3.3)

**Comment by GoSTEAN** [comment]
Hi @tabaktoni Please can this be assign to me. Thank you.

**Comment by ivpavici** [comment]
@GoSTEAN good luck!

**Comment by ivpavici** [comment]
@GoSTEAN hi! any progress?

**Comment by GoSTEAN** [comment]
@ivpavici  yes there is progress and I will be done soon. Thank you for your patience.

**Comment by ivpavici** [comment]
ok if not done until 22nd I will offer this task on the ODHack event
https://onlydust.notion.site/ODHack-Common-Guidelines-b9c6b6a4ac4146d087185568aca38a3f

**Comment by GoSTEAN** [comment]
@ivpavici I have created a PR

**Comment by GoSTEAN** [comment]
@ivpavici https://github.com/starknet-io/starknet.js/pull/1091 the PR

**Comment by ivpavici** [comment]
Abi-wan is reoslved!

But, we have 2 noble-curves versions -> check to remove the older one 
https://pkg-size.dev/starknet@6.11

**Comment by penovicp** [comment]
The duplication for the `@noble` libraries occurred because they are used both directly and as sub-dependencies for one of the `@scure` libraries where they are limited to only patch version updates.

This has been resolved by #1197. Going forward we should aim to keep them aligned.
