### ISSUE TITLE
Why I am not eligible for starknet airdrop sir my address is

0x0326e95A1E7Be0011313C320cF88A57F77fDDE5C330443b35D048E03f9eE794D
I envoved 600 dollar above in this address sir


### ISSUE THREAD

**Issue by Armankhan566** [starknet-io/starknet.js#960]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker]
- Node version [e.g. 16.0.1]
- Starknet.js version
- Network [devnet, testnet]

**Additional context**

**Comment by tabaktoni** [comment]
https://discord.com/channels/793094838509764618/1207218594241318932
