### ISSUE TITLE
To listen to community's voice on airdrop! 

### ISSUE THREAD

**Issue by hengheng20** [starknet-io/starknet.js#962]
**Is your feature request related to a problem? Please describe.**
this is related more to community voice

**Describe the solution you'd like**
to have an independent review on community's opinion

**Describe alternatives you've considered**
alternative would be to have STARK people to give their findings but definitely not as independent

**Comment by penovicp** [comment]
This space is only for technical discussions for `starknet.js`. None of the decision makers from the Starknet Foundation are active here so voicing grievances about their decisions here won't reach them.  Discord and other social media are better avenues for such feedback.
