### ISSUE TITLE
Starknet Speed Option / gas usage as an option for users

### ISSUE THREAD

**Issue by mohamednour12** [starknet-io/starknet.js#963]
Due to RPC/transaction sometime failing
I recommend giving users and developpers option to change fees base on network congestion as it can vary, as a fail transaction will sometime stuck your wallet for a few making it less user friendly.

Gas adjustement is not available currently on starknet wallets.

**Comment by ivpavici** [comment]
hello! this is a potential issue for wallets, not Starknet.js - the library provides an option to set fees
