### ISSUE TITLE
Add ByteArray to UTF* decode utils

### ISSUE THREAD

**Issue by JorikSchellekens** [starknet-io/starknet.js#986]
**Is your feature request related to a problem? Please describe.**
String support is in Cairo but it's annoying for developers to have to think about how to deserialise the ByteArray struct.

**Describe the solution you'd like**
Either provide a function to decode ByteArrays or just do it for them when the abi contains a ByteArray return type.

**Comment by PhilippeR26** [comment]
Hello,
ByteArray is already supported in Starknet.js, both for encoding and decoding :
https://www.starknetjs.com/docs/next/guides/define_call_message#longstring-or-bytearray
https://www.starknetjs.com/docs/next/guides/define_call_message#receive-data-from-a-cairo-contract

**Comment by ivpavici** [comment]
@JorikSchellekens hi! 
Is https://www.starknetjs.com/docs/next/api/namespaces/bytearray/#stringfrombytearray what you are looking for?

**Comment by JorikSchellekens** [comment]
Neither that function nore it's associated namesapce is exported. Besides the abi compiler should just understand this type and compile the strings regardless.

Also the documentation around this is difficult to understand:

![image](https://github.com/starknet-io/starknet.js/assets/23084468/281586d7-c335-4918-a01c-cc4673548307)
